{
  "formatVersion": "1.1",
  "component": {
    "group": "ee.schimke.a2uicmp",
    "module": "material3-a2ui",
    "version": "1.0.0-alpha01-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "ee.schimke.a2uicmp",
          "module": "a2ui-model",
          "version": {
            "requires": "1.0.0-alpha01-cmp01"
          }
        },
        {
          "group": "ee.schimke.a2uicmp",
          "module": "a2ui-compose-runtime",
          "version": {
            "requires": "1.0.0-alpha01-cmp01"
          }
        },
        {
          "group": "ee.schimke.a2uicmp",
          "module": "a2ui-compose-ui",
          "version": {
            "requires": "1.0.0-alpha01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.13.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "material3-a2ui-metadata-1.0.0-alpha01-cmp01.jar",
          "url": "material3-a2ui-1.0.0-alpha01-cmp01.jar",
          "size": 50027,
          "sha512": "b2a6d5fadbbf0615f3fdd5af8f50ea781362d23ab8da0599368ff71ffdd7b02846a8b8fa5d65a6e0f5b04a9d4fa88f15498a3b7d41e898568f3805f993b7f01f",
          "sha256": "58017711f41d2d02e91a18a7b055be10cb1cfea3bdde1ddf6a11ec1bf753a37f",
          "sha1": "3e60066e8763949775e4704a1a0a6a7ab7589f48",
          "md5": "c29a45d51cd12db7610e83b34fb66e60"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "material3-a2ui-kotlin-1.0.0-alpha01-cmp01-sources.jar",
          "url": "material3-a2ui-1.0.0-alpha01-cmp01-sources.jar",
          "size": 123626,
          "sha512": "a222612e133a7365e577e17072156dd77dd0fe0846d97bc69d56fcaa0178015201df27e46667fd96ef4de81bd4e4bedaab6aad1978ea55cbb5f259357fd3b4f8",
          "sha256": "8798f57c00bef8aa2a4978dadd9ae806677b7370bf34c347899a571ccf328633",
          "sha1": "21a84ab165947d43f942448f24a1078286230321",
          "md5": "ac939ed2e5ae9b5ea7543473b8036b83"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-a2ui-jvm/1.0.0-alpha01-cmp01/material3-a2ui-jvm-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "material3-a2ui-jvm",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-a2ui-jvm/1.0.0-alpha01-cmp01/material3-a2ui-jvm-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "material3-a2ui-jvm",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-a2ui-jvm/1.0.0-alpha01-cmp01/material3-a2ui-jvm-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "material3-a2ui-jvm",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../material3-a2ui-wasm-js/1.0.0-alpha01-cmp01/material3-a2ui-wasm-js-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "material3-a2ui-wasm-js",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../material3-a2ui-wasm-js/1.0.0-alpha01-cmp01/material3-a2ui-wasm-js-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "material3-a2ui-wasm-js",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../material3-a2ui-wasm-js/1.0.0-alpha01-cmp01/material3-a2ui-wasm-js-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "material3-a2ui-wasm-js",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../material3-a2ui-wasm-js/1.0.0-alpha01-cmp01/material3-a2ui-wasm-js-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "material3-a2ui-wasm-js",
        "version": "1.0.0-alpha01-cmp01"
      }
    }
  ]
}
