{
  "formatVersion": "1.1",
  "component": {
    "group": "ee.schimke.a2uicmp",
    "module": "a2ui-compose-ui",
    "version": "1.0.0-alpha01-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "ee.schimke.a2uicmp",
          "module": "a2ui-compose-runtime",
          "version": {
            "requires": "1.0.0-alpha01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.13.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.13.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "a2ui-compose-ui-metadata-1.0.0-alpha01-cmp01.jar",
          "url": "a2ui-compose-ui-1.0.0-alpha01-cmp01.jar",
          "size": 10244,
          "sha512": "a8649c14ef318ea7d6e41eb0b9df35a84beff4d924f272e050b35e2dd3f11be3800be9e3c784f9a06e2dbed3ac32928e9d3fdd34f3c71e2c146eb219880a7141",
          "sha256": "434c027fa3135cd876a668c5f5b317a2271e33bd8d2b5e696356f2800b1cb481",
          "sha1": "5ef3f020f1c8c14c8b32549c1be98127f1640f2f",
          "md5": "e208cc1cc4d3340211a71d743dd47f15"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "a2ui-compose-ui-kotlin-1.0.0-alpha01-cmp01-sources.jar",
          "url": "a2ui-compose-ui-1.0.0-alpha01-cmp01-sources.jar",
          "size": 26562,
          "sha512": "97bf56ae4a3c192829179f42e065e5e825c7d4ac6ca2a89504cb77b05971945becae0bcc1880665f9a0eed625aa12e3585e60f6d25e904f412ab6d65225912e9",
          "sha256": "130d1f9cf87528b8ab4fe08913af9e1bd0ae5b0343e13e501f23c191e96f23db",
          "sha1": "8ccc8c9e8635d3049ac0d14532b348ba0fc15701",
          "md5": "4eef5c6aae2ce9cd2f332f49cf92919d"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../a2ui-compose-ui-jvm/1.0.0-alpha01-cmp01/a2ui-compose-ui-jvm-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "a2ui-compose-ui-jvm",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../a2ui-compose-ui-jvm/1.0.0-alpha01-cmp01/a2ui-compose-ui-jvm-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "a2ui-compose-ui-jvm",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../a2ui-compose-ui-jvm/1.0.0-alpha01-cmp01/a2ui-compose-ui-jvm-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "a2ui-compose-ui-jvm",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../a2ui-compose-ui-wasm-js/1.0.0-alpha01-cmp01/a2ui-compose-ui-wasm-js-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "a2ui-compose-ui-wasm-js",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../a2ui-compose-ui-wasm-js/1.0.0-alpha01-cmp01/a2ui-compose-ui-wasm-js-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "a2ui-compose-ui-wasm-js",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../a2ui-compose-ui-wasm-js/1.0.0-alpha01-cmp01/a2ui-compose-ui-wasm-js-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "a2ui-compose-ui-wasm-js",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../a2ui-compose-ui-wasm-js/1.0.0-alpha01-cmp01/a2ui-compose-ui-wasm-js-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "a2ui-compose-ui-wasm-js",
        "version": "1.0.0-alpha01-cmp01"
      }
    }
  ]
}
