{
  "formatVersion": "1.1",
  "component": {
    "url": "../../a2ui-model/1.0.0-alpha01-cmp01/a2ui-model-1.0.0-alpha01-cmp01.module",
    "group": "ee.schimke.a2uicmp",
    "module": "a2ui-model",
    "version": "1.0.0-alpha01-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.a2uicmp",
          "module": "a2ui-port-runtime",
          "version": {
            "requires": "1.0.0-alpha01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "a2ui-model-wasm-js-1.0.0-alpha01-cmp01.klib",
          "url": "a2ui-model-wasm-js-1.0.0-alpha01-cmp01.klib",
          "size": 193435,
          "sha512": "bc25bc42640e4070b0b1542f8cba8986ffb7ae624594e424583e19cf0b42e38efcce2b1e70962e7d99a5d3284e6b5b77cce89c401e518983c570aa2315f43a69",
          "sha256": "930d03a8a476c9becdd24869ac32b32daf6fddef960e350f6d204bbd34ec9b88",
          "sha1": "c5e0c913f56c72019d9de4cfefdc9f85170c2fa0",
          "md5": "7ec03afe9fa66b2cdcef5ef5e03b1aa2"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.a2uicmp",
          "module": "a2ui-port-runtime",
          "version": {
            "requires": "1.0.0-alpha01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "a2ui-model-wasm-js-1.0.0-alpha01-cmp01.klib",
          "url": "a2ui-model-wasm-js-1.0.0-alpha01-cmp01.klib",
          "size": 193435,
          "sha512": "bc25bc42640e4070b0b1542f8cba8986ffb7ae624594e424583e19cf0b42e38efcce2b1e70962e7d99a5d3284e6b5b77cce89c401e518983c570aa2315f43a69",
          "sha256": "930d03a8a476c9becdd24869ac32b32daf6fddef960e350f6d204bbd34ec9b88",
          "sha1": "c5e0c913f56c72019d9de4cfefdc9f85170c2fa0",
          "md5": "7ec03afe9fa66b2cdcef5ef5e03b1aa2"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "a2ui-model-wasm-js-1.0.0-alpha01-cmp01-sources.jar",
          "url": "a2ui-model-wasm-js-1.0.0-alpha01-cmp01-sources.jar",
          "size": 96509,
          "sha512": "9bbb76e9631f22aa6d1c26665fd390a35a796a5aa7862facd5b36eb7fa1bad192795e0cc4581d7b3f90e5e1eedc4f1331b7bef35adc12dd0ae9ce6c2054f6548",
          "sha256": "c88aaa0b6401680ff70ab716abc0da077c41e993e17ac99a20bbd5a962e3bf9d",
          "sha1": "38a05299e39945e5d700a78176687d4b4a183a5b",
          "md5": "598aa802c6487276f8f3b775e88bc422"
        }
      ]
    }
  ]
}
