{
  "formatVersion": "1.1",
  "component": {
    "group": "ee.schimke.a2uicmp",
    "module": "a2ui-compose-runtime",
    "version": "1.0.0-alpha01-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "ee.schimke.a2uicmp",
          "module": "a2ui-model",
          "version": {
            "requires": "1.0.0-alpha01-cmp01"
          }
        },
        {
          "group": "ee.schimke.a2uicmp",
          "module": "a2ui-engine",
          "version": {
            "requires": "1.0.0-alpha01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.13.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "a2ui-compose-runtime-metadata-1.0.0-alpha01-cmp01.jar",
          "url": "a2ui-compose-runtime-1.0.0-alpha01-cmp01.jar",
          "size": 14394,
          "sha512": "2b1342486a78887239f7d9e60dff9c1892ad172d9aa949b985a0981b815b3313f602ee293f0d4bb5e3ecad5c5cda74f20631454866d27b2b611e4329add76ab8",
          "sha256": "f879c421ef0d99616757556786fa21f47143367b6399a33fb5f82bd3b16be0f9",
          "sha1": "c6cf7f486a88190223cca7ef8dcc18cc40ec5118",
          "md5": "fae013ad4b252190f73e1cd4f5284e74"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "a2ui-compose-runtime-kotlin-1.0.0-alpha01-cmp01-sources.jar",
          "url": "a2ui-compose-runtime-1.0.0-alpha01-cmp01-sources.jar",
          "size": 33308,
          "sha512": "a9d8252ca75fdf66a3d154be262c7badbd57ab7f8113d30a7e3587167e31d320ea7ce1fc02cd2a9661098e1322459ba6c5b0863ce47cbbfc5bccf1b5e518d804",
          "sha256": "2c0ecae2f3cd283071cbc658ee7b6f8eb52932b8246381f902345d699aab5d94",
          "sha1": "4d7e3a93067e6921a0e43c9c132474aacdc6ebbd",
          "md5": "7c8a35b4cbe77d52eb5bd0ab73035944"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../a2ui-compose-runtime-jvm/1.0.0-alpha01-cmp01/a2ui-compose-runtime-jvm-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "a2ui-compose-runtime-jvm",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../a2ui-compose-runtime-jvm/1.0.0-alpha01-cmp01/a2ui-compose-runtime-jvm-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "a2ui-compose-runtime-jvm",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../a2ui-compose-runtime-jvm/1.0.0-alpha01-cmp01/a2ui-compose-runtime-jvm-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "a2ui-compose-runtime-jvm",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../a2ui-compose-runtime-wasm-js/1.0.0-alpha01-cmp01/a2ui-compose-runtime-wasm-js-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "a2ui-compose-runtime-wasm-js",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../a2ui-compose-runtime-wasm-js/1.0.0-alpha01-cmp01/a2ui-compose-runtime-wasm-js-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "a2ui-compose-runtime-wasm-js",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../a2ui-compose-runtime-wasm-js/1.0.0-alpha01-cmp01/a2ui-compose-runtime-wasm-js-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "a2ui-compose-runtime-wasm-js",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../a2ui-compose-runtime-wasm-js/1.0.0-alpha01-cmp01/a2ui-compose-runtime-wasm-js-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "a2ui-compose-runtime-wasm-js",
        "version": "1.0.0-alpha01-cmp01"
      }
    }
  ]
}
