{
  "formatVersion": "1.1",
  "component": {
    "url": "../../a2ui-port-runtime/1.0.0-alpha01-cmp01/a2ui-port-runtime-1.0.0-alpha01-cmp01.module",
    "group": "ee.schimke.a2uicmp",
    "module": "a2ui-port-runtime",
    "version": "1.0.0-alpha01-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "a2ui-port-runtime-wasm-js-1.0.0-alpha01-cmp01.klib",
          "url": "a2ui-port-runtime-wasm-js-1.0.0-alpha01-cmp01.klib",
          "size": 67975,
          "sha512": "78aa7256284360b9a02cdfd83ae414eca5eab899a3b5c27693b6b5c6f97f0f1c47c4cca595034c619a9f0bba4b3d97a57b030f905c2f12525d15f6e78fd088eb",
          "sha256": "dd256261595119bc562d320593f70b05f16a77b2401f3bfda4c5c78cf05cc5f1",
          "sha1": "6df6a3302fdc340b12bd80fc5ac0b1cacf07f4ff",
          "md5": "67d0422ad08f826292673fe126f8b2a5"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "a2ui-port-runtime-wasm-js-1.0.0-alpha01-cmp01.klib",
          "url": "a2ui-port-runtime-wasm-js-1.0.0-alpha01-cmp01.klib",
          "size": 67975,
          "sha512": "78aa7256284360b9a02cdfd83ae414eca5eab899a3b5c27693b6b5c6f97f0f1c47c4cca595034c619a9f0bba4b3d97a57b030f905c2f12525d15f6e78fd088eb",
          "sha256": "dd256261595119bc562d320593f70b05f16a77b2401f3bfda4c5c78cf05cc5f1",
          "sha1": "6df6a3302fdc340b12bd80fc5ac0b1cacf07f4ff",
          "md5": "67d0422ad08f826292673fe126f8b2a5"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "a2ui-port-runtime-wasm-js-1.0.0-alpha01-cmp01-sources.jar",
          "url": "a2ui-port-runtime-wasm-js-1.0.0-alpha01-cmp01-sources.jar",
          "size": 16186,
          "sha512": "04dbcd19e3c8212c85f2743256dd591665739c2932eb524abffb5894f22746445d6c96a311acc41dca8713a6c371a99af8f7725673d4a18629fc43292644b62a",
          "sha256": "a3c3f0a9cafd1e656cca87a83b4fe57daa1dab10dbb07ecd11f08508b836ef42",
          "sha1": "4e247208ba5bdb816e328aee2089de22d910426d",
          "md5": "2d67dd56077aa2991da94febc189cc0c"
        }
      ]
    }
  ]
}
