{
  "formatVersion": "1.1",
  "component": {
    "group": "ee.schimke.a2uicmp",
    "module": "a2ui-port-runtime",
    "version": "1.0.0-alpha01-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "a2ui-port-runtime-metadata-1.0.0-alpha01-cmp01.jar",
          "url": "a2ui-port-runtime-1.0.0-alpha01-cmp01.jar",
          "size": 8001,
          "sha512": "b129a6f2607dd566ac82abbfc4729e366b3a039b84571f52bf6bd34a6fac679a212cd3339c3e5a688ea791b05c12fd55384df7ddccc792c4d49ed78ccb9eac44",
          "sha256": "7be07cbc8942018d8c900482e073ca5f1fb2cebb8efe47773760572cc8bee884",
          "sha1": "6d255d6612036b4ba6b11ef456b14fde779aa13c",
          "md5": "9641f0b9a36ea604596bafecc5adc169"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "a2ui-port-runtime-kotlin-1.0.0-alpha01-cmp01-sources.jar",
          "url": "a2ui-port-runtime-1.0.0-alpha01-cmp01-sources.jar",
          "size": 8769,
          "sha512": "baec99d99b2624e6b7ca4eadb0184684dca4c9ce3dfef87e03178f267206e0fd550087a02d35125936b9f195d7e1f94633550fc4694613b12f33e6c226e6869d",
          "sha256": "cd1e6f9aff80d944c1759351a00f67c83f7fe74b21f899e0c8f6a717192adffa",
          "sha1": "b378b776b8ce5eab5d640c63cf5c7f7c987469a6",
          "md5": "72d5d76af71ebd8ac1b06f9af31a66b3"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../a2ui-port-runtime-jvm/1.0.0-alpha01-cmp01/a2ui-port-runtime-jvm-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "a2ui-port-runtime-jvm",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../a2ui-port-runtime-jvm/1.0.0-alpha01-cmp01/a2ui-port-runtime-jvm-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "a2ui-port-runtime-jvm",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../a2ui-port-runtime-jvm/1.0.0-alpha01-cmp01/a2ui-port-runtime-jvm-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "a2ui-port-runtime-jvm",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../a2ui-port-runtime-wasm-js/1.0.0-alpha01-cmp01/a2ui-port-runtime-wasm-js-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "a2ui-port-runtime-wasm-js",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../a2ui-port-runtime-wasm-js/1.0.0-alpha01-cmp01/a2ui-port-runtime-wasm-js-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "a2ui-port-runtime-wasm-js",
        "version": "1.0.0-alpha01-cmp01"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../a2ui-port-runtime-wasm-js/1.0.0-alpha01-cmp01/a2ui-port-runtime-wasm-js-1.0.0-alpha01-cmp01.module",
        "group": "ee.schimke.a2uicmp",
        "module": "a2ui-port-runtime-wasm-js",
        "version": "1.0.0-alpha01-cmp01"
      }
    }
  ]
}
