{
  "formatVersion": "1.1",
  "component": {
    "url": "../../a2ui-compose-ui/1.0.0-alpha01-cmp01/a2ui-compose-ui-1.0.0-alpha01-cmp01.module",
    "group": "ee.schimke.a2uicmp",
    "module": "a2ui-compose-ui",
    "version": "1.0.0-alpha01-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ee.schimke.a2uicmp",
          "module": "a2ui-compose-runtime",
          "version": {
            "requires": "1.0.0-alpha01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.13.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.13.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "a2ui-compose-ui-jvm-1.0.0-alpha01-cmp01.jar",
          "url": "a2ui-compose-ui-jvm-1.0.0-alpha01-cmp01.jar",
          "size": 258059,
          "sha512": "52a47f3df408a806a4d3578d1663102adfc688af5f84ae3f167f256c6b50ed48c8cd4c8b15a65df62ce2cf845c7eeb59fac09a28de657923844cb906106c3cae",
          "sha256": "aceb6df0b15ec4c429ff35d5da4973ddcddf16510fae6421210d171abc993fb6",
          "sha1": "cffab7268d16329e47172ae1b1c30d218f83248a",
          "md5": "8dedc48491db3ddcec871ae8629ec707"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ee.schimke.a2uicmp",
          "module": "a2ui-compose-runtime",
          "version": {
            "requires": "1.0.0-alpha01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.13.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.13.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "ee.schimke.a2uicmp",
          "module": "a2ui-port-runtime",
          "version": {
            "requires": "1.0.0-alpha01-cmp01"
          }
        },
        {
          "group": "ee.schimke.a2uicmp",
          "module": "a2ui-engine",
          "version": {
            "requires": "1.0.0-alpha01-cmp01"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "a2ui-compose-ui-jvm-1.0.0-alpha01-cmp01.jar",
          "url": "a2ui-compose-ui-jvm-1.0.0-alpha01-cmp01.jar",
          "size": 258059,
          "sha512": "52a47f3df408a806a4d3578d1663102adfc688af5f84ae3f167f256c6b50ed48c8cd4c8b15a65df62ce2cf845c7eeb59fac09a28de657923844cb906106c3cae",
          "sha256": "aceb6df0b15ec4c429ff35d5da4973ddcddf16510fae6421210d171abc993fb6",
          "sha1": "cffab7268d16329e47172ae1b1c30d218f83248a",
          "md5": "8dedc48491db3ddcec871ae8629ec707"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "a2ui-compose-ui-jvm-1.0.0-alpha01-cmp01-sources.jar",
          "url": "a2ui-compose-ui-jvm-1.0.0-alpha01-cmp01-sources.jar",
          "size": 26562,
          "sha512": "97bf56ae4a3c192829179f42e065e5e825c7d4ac6ca2a89504cb77b05971945becae0bcc1880665f9a0eed625aa12e3585e60f6d25e904f412ab6d65225912e9",
          "sha256": "130d1f9cf87528b8ab4fe08913af9e1bd0ae5b0343e13e501f23c191e96f23db",
          "sha1": "8ccc8c9e8635d3049ac0d14532b348ba0fc15701",
          "md5": "4eef5c6aae2ce9cd2f332f49cf92919d"
        }
      ]
    }
  ]
}
