{
  "formatVersion": "1.1",
  "component": {
    "url": "../../a2ui-compose-runtime/1.0.0-alpha01-cmp01/a2ui-compose-runtime-1.0.0-alpha01-cmp01.module",
    "group": "ee.schimke.a2uicmp",
    "module": "a2ui-compose-runtime",
    "version": "1.0.0-alpha01-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.a2uicmp",
          "module": "a2ui-model",
          "version": {
            "requires": "1.0.0-alpha01-cmp01"
          }
        },
        {
          "group": "ee.schimke.a2uicmp",
          "module": "a2ui-engine",
          "version": {
            "requires": "1.0.0-alpha01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.13.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "a2ui-compose-runtime-wasm-js-1.0.0-alpha01-cmp01.klib",
          "url": "a2ui-compose-runtime-wasm-js-1.0.0-alpha01-cmp01.klib",
          "size": 107350,
          "sha512": "3b1ce0e347b9dd173165cc034961f22378b263ec333a66b3af6e2dbe1107abf3da4841ce69f78235828a3b035616d0f3231107e8f3e427d698e0a34ff9910d8d",
          "sha256": "8e259932f722abd5237a41b248104a07dba3e7ee415a150511f73e01c10a1e75",
          "sha1": "16ef1af302f57c4134392bd9c7ad2382edae2b8f",
          "md5": "b834677dd9656875a786d6c216f4000c"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.a2uicmp",
          "module": "a2ui-model",
          "version": {
            "requires": "1.0.0-alpha01-cmp01"
          }
        },
        {
          "group": "ee.schimke.a2uicmp",
          "module": "a2ui-engine",
          "version": {
            "requires": "1.0.0-alpha01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.13.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "ee.schimke.a2uicmp",
          "module": "a2ui-port-runtime",
          "version": {
            "requires": "1.0.0-alpha01-cmp01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "a2ui-compose-runtime-wasm-js-1.0.0-alpha01-cmp01.klib",
          "url": "a2ui-compose-runtime-wasm-js-1.0.0-alpha01-cmp01.klib",
          "size": 107350,
          "sha512": "3b1ce0e347b9dd173165cc034961f22378b263ec333a66b3af6e2dbe1107abf3da4841ce69f78235828a3b035616d0f3231107e8f3e427d698e0a34ff9910d8d",
          "sha256": "8e259932f722abd5237a41b248104a07dba3e7ee415a150511f73e01c10a1e75",
          "sha1": "16ef1af302f57c4134392bd9c7ad2382edae2b8f",
          "md5": "b834677dd9656875a786d6c216f4000c"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "a2ui-compose-runtime-wasm-js-1.0.0-alpha01-cmp01-sources.jar",
          "url": "a2ui-compose-runtime-wasm-js-1.0.0-alpha01-cmp01-sources.jar",
          "size": 33308,
          "sha512": "a9d8252ca75fdf66a3d154be262c7badbd57ab7f8113d30a7e3587167e31d320ea7ce1fc02cd2a9661098e1322459ba6c5b0863ce47cbbfc5bccf1b5e518d804",
          "sha256": "2c0ecae2f3cd283071cbc658ee7b6f8eb52932b8246381f902345d699aab5d94",
          "sha1": "4d7e3a93067e6921a0e43c9c132474aacdc6ebbd",
          "md5": "7c8a35b4cbe77d52eb5bd0ab73035944"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.a2uicmp",
          "module": "a2ui-model",
          "version": {
            "requires": "1.0.0-alpha01-cmp01"
          }
        },
        {
          "group": "ee.schimke.a2uicmp",
          "module": "a2ui-engine",
          "version": {
            "requires": "1.0.0-alpha01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.13.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "ee.schimke.a2uicmp",
          "module": "a2ui-port-runtime",
          "version": {
            "requires": "1.0.0-alpha01-cmp01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "a2ui-compose-runtime-1.0.0-alpha01-cmp01.kotlin_resources.zip",
          "url": "a2ui-compose-runtime-wasm-js-1.0.0-alpha01-cmp01-kotlin_resources.kotlin_resources.zip",
          "size": 366,
          "sha512": "30c2aea9b4a37bd56d71931b3d2f261e9cb789c8d72c187ec0dd7dc0f3148f7328f494be708a64196dfd76d20536520442dcf6d3e8f121adf980533de4444f35",
          "sha256": "c59590e55ac266f11ae6058449d1e0c751a12c47bdb20ca31168ebc1f397299b",
          "sha1": "4c21010c6db2f88bd05ef0e1076d02a3072a675f",
          "md5": "7b538d80fbe3e2489deaa61f00c5f806"
        }
      ]
    }
  ]
}
